apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.label }}"
  replicas: 1
  template:
    metadata: 
        name: "{{ .Values.podname }}"
        namespace: "{{ .Values.namespace }}"
        labels:
          app: "{{ .Values.label }}"
    spec:
      containers:
        - name: "{{ .Values.containerName }}"
          image: "{{ .Values.imageName }}:latest"
          imagePullPolicy: Never   
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: PORT
              value: "{{ .Values.APP.PORT }}"
            - name: NODE_ENV
              value: "{{ .Values.APP.NODE_ENV }}"
            - name: KUBEDOC_TEST_BASE_URL
              value: "{{ .Values.APP.KUBEDOC_TEST_BASE_URL }}"