apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.APP.HELLO_CRONJOB }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.APP.HELLO_CRONJOB }}
              image: curlimages/curl
              imagePullPolicy: Always
              command:
                [
                  '/bin/sh',
                  '-c',
                  'curl --insecure  -X GET {{ .Values.APP.KUBEDOC_TEST_BASE_URL }}/hello'
                ]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
