apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.serviceName }}"
spec:
  selector:
    app: "{{ .Values.label }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.TargetPort }}
  type: ClusterIP
