apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: personal-projects
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-cronjob
              image: curlimages/curl
              imagePullPolicy: Always
              command:
                [
                  '/bin/sh',
                  '-c',
                  'curl --insecure  -X GET http://kubedoc-test.personal-projects/hello'
                ]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
