apiVersion: v1
kind: Service
metadata:
  namespace: personal-projects
  name: kubedoc-test
spec:
  selector:
    app: kubedoc-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
